// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Conv,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=15,HLS_SYN_FF=3644,HLS_SYN_LUT=3487,HLS_VERSION=2018_3}" *)

module Conv (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 68'd1;
parameter    ap_ST_fsm_state2 = 68'd2;
parameter    ap_ST_fsm_state3 = 68'd4;
parameter    ap_ST_fsm_state4 = 68'd8;
parameter    ap_ST_fsm_state5 = 68'd16;
parameter    ap_ST_fsm_state6 = 68'd32;
parameter    ap_ST_fsm_state7 = 68'd64;
parameter    ap_ST_fsm_state8 = 68'd128;
parameter    ap_ST_fsm_state9 = 68'd256;
parameter    ap_ST_fsm_state10 = 68'd512;
parameter    ap_ST_fsm_state11 = 68'd1024;
parameter    ap_ST_fsm_state12 = 68'd2048;
parameter    ap_ST_fsm_state13 = 68'd4096;
parameter    ap_ST_fsm_state14 = 68'd8192;
parameter    ap_ST_fsm_state15 = 68'd16384;
parameter    ap_ST_fsm_state16 = 68'd32768;
parameter    ap_ST_fsm_state17 = 68'd65536;
parameter    ap_ST_fsm_state18 = 68'd131072;
parameter    ap_ST_fsm_state19 = 68'd262144;
parameter    ap_ST_fsm_state20 = 68'd524288;
parameter    ap_ST_fsm_state21 = 68'd1048576;
parameter    ap_ST_fsm_state22 = 68'd2097152;
parameter    ap_ST_fsm_state23 = 68'd4194304;
parameter    ap_ST_fsm_state24 = 68'd8388608;
parameter    ap_ST_fsm_state25 = 68'd16777216;
parameter    ap_ST_fsm_state26 = 68'd33554432;
parameter    ap_ST_fsm_state27 = 68'd67108864;
parameter    ap_ST_fsm_state28 = 68'd134217728;
parameter    ap_ST_fsm_state29 = 68'd268435456;
parameter    ap_ST_fsm_state30 = 68'd536870912;
parameter    ap_ST_fsm_state31 = 68'd1073741824;
parameter    ap_ST_fsm_state32 = 68'd2147483648;
parameter    ap_ST_fsm_state33 = 68'd4294967296;
parameter    ap_ST_fsm_state34 = 68'd8589934592;
parameter    ap_ST_fsm_state35 = 68'd17179869184;
parameter    ap_ST_fsm_state36 = 68'd34359738368;
parameter    ap_ST_fsm_state37 = 68'd68719476736;
parameter    ap_ST_fsm_state38 = 68'd137438953472;
parameter    ap_ST_fsm_state39 = 68'd274877906944;
parameter    ap_ST_fsm_state40 = 68'd549755813888;
parameter    ap_ST_fsm_state41 = 68'd1099511627776;
parameter    ap_ST_fsm_state42 = 68'd2199023255552;
parameter    ap_ST_fsm_state43 = 68'd4398046511104;
parameter    ap_ST_fsm_state44 = 68'd8796093022208;
parameter    ap_ST_fsm_state45 = 68'd17592186044416;
parameter    ap_ST_fsm_state46 = 68'd35184372088832;
parameter    ap_ST_fsm_state47 = 68'd70368744177664;
parameter    ap_ST_fsm_state48 = 68'd140737488355328;
parameter    ap_ST_fsm_state49 = 68'd281474976710656;
parameter    ap_ST_fsm_state50 = 68'd562949953421312;
parameter    ap_ST_fsm_state51 = 68'd1125899906842624;
parameter    ap_ST_fsm_state52 = 68'd2251799813685248;
parameter    ap_ST_fsm_state53 = 68'd4503599627370496;
parameter    ap_ST_fsm_state54 = 68'd9007199254740992;
parameter    ap_ST_fsm_state55 = 68'd18014398509481984;
parameter    ap_ST_fsm_state56 = 68'd36028797018963968;
parameter    ap_ST_fsm_state57 = 68'd72057594037927936;
parameter    ap_ST_fsm_state58 = 68'd144115188075855872;
parameter    ap_ST_fsm_state59 = 68'd288230376151711744;
parameter    ap_ST_fsm_state60 = 68'd576460752303423488;
parameter    ap_ST_fsm_state61 = 68'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 68'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 68'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 68'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 68'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 68'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 68'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 68'd147573952589676412928;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 32;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [67:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] CHin_V;
wire   [15:0] Hin_V;
wire   [15:0] Win_V;
wire   [15:0] CHout_V;
wire   [7:0] Kx_V;
wire   [7:0] Ky_V;
wire   [7:0] Sx_V;
wire   [7:0] Sy_V;
wire   [0:0] mode_V;
wire   [0:0] relu_en_V;
wire   [31:0] feature_in;
wire   [31:0] W;
wire   [31:0] bias;
wire   [31:0] feature_out;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state29;
wire   [0:0] exitcond4_fu_916_p2;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state57;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state42;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state62;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state63;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state68;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [31:0] gmem_ARADDR;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg   [0:0] relu_en_V_read_reg_1219;
reg   [7:0] Sy_V_read_reg_1224;
reg   [7:0] Sx_V_read_reg_1230;
reg   [7:0] Ky_V_read_reg_1236;
reg   [7:0] Kx_V_read_reg_1242;
reg   [15:0] CHout_V_read_reg_1249;
reg   [15:0] Win_V_read_reg_1256;
reg   [15:0] Hin_V_read_reg_1262;
reg   [15:0] CHin_V_read_reg_1267;
reg   [29:0] tmp_1_reg_1274;
reg   [29:0] tmp_2_reg_1279;
reg   [29:0] tmp_4_reg_1284;
reg   [29:0] tmp_5_reg_1289;
wire   [7:0] p_s_fu_644_p3;
reg   [7:0] p_s_reg_1294;
wire   [7:0] p_1_fu_652_p3;
reg   [7:0] p_1_reg_1300;
wire   [16:0] lhs_V_2_cast_fu_671_p1;
reg   [16:0] lhs_V_2_cast_reg_1306;
wire    ap_CS_fsm_state2;
wire   [16:0] lhs_V_4_cast_fu_717_p1;
reg   [16:0] lhs_V_4_cast_reg_1321;
wire   [48:0] tmp_2_cast1_fu_752_p1;
reg   [48:0] tmp_2_cast1_reg_1336;
wire    ap_CS_fsm_state24;
wire   [30:0] tmp_8_cast_fu_755_p1;
reg   [30:0] tmp_8_cast_reg_1341;
wire   [48:0] tmp_12_cast_fu_758_p1;
reg   [48:0] tmp_12_cast_reg_1346;
wire   [47:0] tmp_15_cast_fu_761_p1;
reg   [47:0] tmp_15_cast_reg_1351;
wire   [15:0] Wout_V_fu_768_p2;
reg   [15:0] Wout_V_reg_1356;
wire   [15:0] tmp_7_fu_778_p2;
reg   [15:0] tmp_7_reg_1361;
wire   [15:0] tmp_9_fu_784_p1;
reg   [15:0] tmp_9_reg_1366;
wire   [15:0] tmp_s_fu_787_p1;
reg   [15:0] tmp_s_reg_1371;
wire   [31:0] rhs_V_1_cast_fu_790_p1;
reg   [31:0] rhs_V_1_cast_reg_1376;
wire   [31:0] rhs_V_fu_794_p1;
reg   [31:0] rhs_V_reg_1381;
wire   [15:0] tmp_21_fu_797_p1;
reg   [15:0] tmp_21_reg_1388;
wire   [15:0] tmp_22_fu_800_p1;
reg   [15:0] tmp_22_reg_1393;
wire   [47:0] rhs_V_1_fu_803_p1;
reg   [47:0] rhs_V_1_reg_1398;
wire   [15:0] rhs_V_15_cast_fu_806_p1;
reg   [15:0] rhs_V_15_cast_reg_1403;
wire   [47:0] rhs_V_12_cast1_fu_809_p1;
reg   [47:0] rhs_V_12_cast1_reg_1408;
wire   [23:0] rhs_V_13_cast_fu_812_p1;
reg   [23:0] rhs_V_13_cast_reg_1414;
wire   [31:0] rhs_V_14_cast_fu_815_p1;
reg   [31:0] rhs_V_14_cast_reg_1419;
wire   [15:0] cout_fu_823_p2;
reg   [15:0] cout_reg_1428;
wire    ap_CS_fsm_state25;
wire   [31:0] tmp_10_cast_fu_833_p1;
reg   [31:0] tmp_10_cast_reg_1433;
wire   [0:0] exitcond5_fu_818_p2;
reg   [31:0] gmem_addr_reg_1439;
wire   [15:0] next_mul1_fu_852_p2;
reg   [15:0] next_mul1_reg_1445;
wire    ap_CS_fsm_state26;
wire   [15:0] i_fu_866_p2;
reg   [15:0] i_reg_1453;
wire   [31:0] ret_V_fu_1198_p2;
reg   [31:0] ret_V_reg_1458;
wire   [0:0] exitcond1_fu_861_p2;
wire   [15:0] tmp_23_fu_872_p2;
reg   [15:0] tmp_23_reg_1463;
wire   [47:0] ret_V_1_fu_880_p2;
reg   [47:0] ret_V_1_reg_1468;
wire    ap_CS_fsm_state27;
wire   [15:0] next_mul2_fu_885_p2;
reg   [15:0] next_mul2_reg_1473;
wire    ap_CS_fsm_state28;
wire   [31:0] next_mul3_fu_890_p2;
reg   [31:0] next_mul3_reg_1478;
wire   [15:0] j_fu_900_p2;
reg   [15:0] j_reg_1486;
wire   [15:0] tmp_24_fu_906_p2;
reg   [15:0] tmp_24_reg_1491;
wire   [0:0] exitcond_fu_895_p2;
wire   [15:0] next_mul4_fu_911_p2;
reg   [15:0] next_mul4_reg_1496;
reg    ap_sig_ioackin_gmem_ARREADY;
reg    ap_block_state29_io;
wire   [7:0] ii_fu_921_p2;
reg   [7:0] ii_reg_1504;
wire  signed [15:0] h_V_fu_931_p2;
reg  signed [15:0] h_V_reg_1509;
wire  signed [31:0] ret_V_9_fu_1203_p2;
reg  signed [31:0] ret_V_9_reg_1514;
wire   [0:0] slt_fu_944_p2;
reg   [0:0] slt_reg_1519;
reg   [31:0] gmem_addr_1_reg_1524;
wire   [47:0] ret_V_14_fu_985_p2;
reg   [47:0] ret_V_14_reg_1530;
wire    ap_CS_fsm_state30;
wire   [31:0] ret_V_10_fu_1208_p2;
reg   [31:0] ret_V_10_reg_1535;
wire   [0:0] rev_fu_994_p2;
reg   [0:0] rev_reg_1540;
wire   [23:0] next_mul5_fu_999_p2;
reg   [23:0] next_mul5_reg_1545;
wire    ap_CS_fsm_state31;
wire   [7:0] jj_fu_1009_p2;
reg   [7:0] jj_reg_1553;
wire  signed [47:0] grp_fu_1213_p3;
reg  signed [47:0] ret_V_12_reg_1564;
wire   [0:0] exitcond3_fu_1004_p2;
wire   [0:0] brmerge_fu_1037_p2;
wire   [0:0] tmp_33_fu_1050_p2;
(* use_dsp48 = "no" *) wire   [31:0] tmp_fu_1059_p2;
reg   [31:0] tmp_reg_1569;
wire   [47:0] tmp1_fu_1067_p2;
reg   [47:0] tmp1_reg_1574;
wire    ap_CS_fsm_state32;
wire   [15:0] cin_fu_1077_p2;
reg   [15:0] cin_reg_1582;
wire    ap_CS_fsm_state33;
reg   [31:0] gmem_addr_2_reg_1587;
wire   [0:0] exitcond2_fu_1072_p2;
wire   [31:0] next_mul_fu_1107_p2;
reg   [31:0] next_mul_reg_1593;
reg   [31:0] gmem_addr_3_reg_1598;
reg   [31:0] gmem_addr_2_read_reg_1604;
reg   [31:0] gmem_addr_3_read_reg_1609;
wire   [31:0] grp_fu_479_p2;
reg   [31:0] tp_reg_1614;
wire    ap_CS_fsm_state45;
wire   [31:0] grp_fu_473_p2;
wire    ap_CS_fsm_state49;
reg   [31:0] gmem_addr_read_reg_1624;
reg   [31:0] sum_3_reg_1629;
wire    ap_CS_fsm_state61;
wire   [31:0] sum_4_fu_1191_p3;
reg   [31:0] sum_4_reg_1636;
reg    ap_sig_ioackin_gmem_AWREADY;
reg   [15:0] i_op_assign_s_reg_288;
reg   [15:0] i_op_assign_1_reg_299;
reg   [15:0] phi_mul1_reg_310;
reg   [15:0] i_op_assign_2_reg_321;
reg   [31:0] ret_V_5_reg_332;
reg   [15:0] phi_mul3_reg_344;
reg   [31:0] sum_reg_355;
reg   [7:0] i_op_assign_3_reg_367;
reg   [15:0] ret_V_16_reg_378;
reg   [31:0] sum_1_reg_390;
wire    ap_CS_fsm_state50;
reg   [7:0] i_op_assign_4_reg_402;
reg   [23:0] ret_V_17_reg_413;
reg   [31:0] sum_2_reg_424;
reg   [15:0] i_op_assign_reg_435;
reg   [31:0] ret_V_18_reg_446;
reg   [31:0] sum_1_be_reg_457;
wire   [63:0] bias6_sum_cast_fu_842_p1;
wire   [63:0] feature_out8_sum_cas_fu_972_p1;
wire  signed [63:0] feature_in2_sum9_cas_fu_1097_p1;
wire   [63:0] W4_sum_cast_fu_1135_p1;
reg    ap_reg_ioackin_gmem_ARREADY;
reg    ap_reg_ioackin_gmem_AWREADY;
reg    ap_reg_ioackin_gmem_WREADY;
reg    ap_sig_ioackin_gmem_WREADY;
reg   [31:0] grp_fu_473_p0;
reg   [31:0] grp_fu_473_p1;
wire    ap_CS_fsm_state46;
wire    ap_CS_fsm_state58;
wire    ap_CS_fsm_state43;
wire   [8:0] tmp_2_cast_fu_528_p1;
wire   [8:0] ret_V_tr_fu_532_p2;
wire   [8:0] p_neg9_fu_546_p2;
wire   [7:0] tmp_3_fu_552_p4;
wire   [0:0] tmp_8_fu_538_p3;
wire   [7:0] tmp_6_fu_572_p2;
wire   [7:0] tmp_10_fu_562_p4;
wire   [8:0] tmp_16_cast_fu_586_p1;
wire   [8:0] ret_V_1_tr_fu_590_p2;
wire   [8:0] p_neg_fu_604_p2;
wire   [7:0] tmp_12_fu_610_p4;
wire   [0:0] tmp_11_fu_596_p3;
wire   [7:0] tmp_14_fu_630_p2;
wire   [7:0] tmp_13_fu_620_p4;
wire   [7:0] pad_x_V_fu_578_p3;
wire   [7:0] pad_y_V_fu_636_p3;
wire   [8:0] ret_V_2_fu_660_p3;
wire   [16:0] ret_V_2_cast_fu_667_p1;
wire   [16:0] ret_V_3_fu_674_p2;
wire   [17:0] ret_V_3_cast_fu_680_p1;
wire   [17:0] rhs_V_2_cast_fu_684_p1;
wire   [17:0] ret_V_4_fu_687_p2;
wire  signed [18:0] grp_fu_700_p0;
wire   [8:0] grp_fu_700_p1;
wire   [8:0] ret_V_6_fu_706_p3;
wire   [16:0] ret_V_6_cast_fu_713_p1;
wire   [16:0] ret_V_7_fu_720_p2;
wire   [17:0] ret_V_7_cast_fu_726_p1;
wire   [17:0] rhs_V_5_cast_fu_730_p1;
wire   [17:0] ret_V_8_fu_733_p2;
wire  signed [18:0] grp_fu_746_p0;
wire   [8:0] grp_fu_746_p1;
wire   [15:0] grp_fu_700_p2;
wire   [15:0] tmp_16_fu_764_p1;
wire   [15:0] grp_fu_746_p2;
wire   [15:0] tmp_19_fu_774_p1;
wire   [30:0] tmp_10_cast1_fu_829_p1;
wire   [30:0] bias6_sum_fu_837_p2;
wire   [31:0] ret_V_1_fu_880_p0;
wire   [15:0] ret_V_1_fu_880_p1;
wire   [15:0] tmp_18_fu_927_p1;
wire  signed [16:0] lhs_V_7_cast_fu_940_p1;
wire   [31:0] tmp3_fu_949_p2;
wire   [47:0] tmp3_cast_fu_954_p1;
wire   [47:0] tmp_20_fu_958_p2;
wire   [48:0] tmp_20_cast_cast_fu_963_p1;
wire   [48:0] feature_out8_sum_fu_967_p2;
wire  signed [31:0] ret_V_14_fu_985_p0;
wire   [15:0] ret_V_14_fu_985_p1;
wire   [15:0] tmp_29_fu_1015_p1;
wire  signed [15:0] w_V_fu_1019_p2;
wire   [15:0] tmp_30_fu_1024_p2;
wire   [0:0] tmp_32_fu_1029_p3;
wire  signed [16:0] lhs_V_5_cast_fu_1046_p1;
wire   [31:0] lhs_V_12_cast_fu_1055_p1;
wire   [31:0] tmp1_fu_1067_p0;
wire   [15:0] tmp1_fu_1067_p1;
wire   [47:0] rhs_V_10_cast_fu_1083_p1;
(* use_dsp48 = "no" *) wire   [47:0] ret_V_15_fu_1087_p2;
wire   [47:0] feature_in2_sum9_fu_1092_p2;
wire   [31:0] tmp2_fu_1112_p2;
wire   [47:0] tmp2_cast_fu_1117_p1;
wire   [47:0] tmp_34_fu_1121_p2;
wire   [48:0] tmp_40_cast_cast_fu_1126_p1;
wire   [48:0] W4_sum_fu_1130_p2;
wire   [31:0] sum_5_to_int_fu_1145_p1;
wire   [7:0] tmp_25_fu_1148_p4;
wire   [22:0] tmp_26_fu_1158_p1;
wire   [0:0] notrhs_fu_1168_p2;
wire   [0:0] notlhs_fu_1162_p2;
wire   [0:0] tmp_27_fu_1174_p2;
wire   [0:0] tmp_28_fu_483_p2;
wire   [0:0] tmp_31_fu_1180_p2;
wire   [0:0] or_cond_fu_1186_p2;
wire   [15:0] ret_V_fu_1198_p0;
wire   [15:0] ret_V_fu_1198_p1;
wire   [15:0] ret_V_9_fu_1203_p1;
wire   [15:0] ret_V_10_fu_1208_p0;
wire   [15:0] ret_V_10_fu_1208_p1;
wire   [15:0] grp_fu_1213_p1;
reg    grp_fu_700_ap_start;
wire    grp_fu_700_ap_done;
reg    grp_fu_746_ap_start;
wire    grp_fu_746_ap_done;
reg   [67:0] ap_NS_fsm;
wire   [18:0] grp_fu_700_p10;
wire   [18:0] grp_fu_746_p10;
wire   [31:0] ret_V_10_fu_1208_p00;
wire   [47:0] ret_V_1_fu_880_p00;
wire   [31:0] ret_V_fu_1198_p00;
wire   [47:0] tmp1_fu_1067_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 68'd1;
#0 ap_reg_ioackin_gmem_ARREADY = 1'b0;
#0 ap_reg_ioackin_gmem_AWREADY = 1'b0;
#0 ap_reg_ioackin_gmem_WREADY = 1'b0;
end

Conv_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
Conv_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .CHin_V(CHin_V),
    .Hin_V(Hin_V),
    .Win_V(Win_V),
    .CHout_V(CHout_V),
    .Kx_V(Kx_V),
    .Ky_V(Ky_V),
    .Sx_V(Sx_V),
    .Sy_V(Sy_V),
    .mode_V(mode_V),
    .relu_en_V(relu_en_V),
    .feature_in(feature_in),
    .W(W),
    .bias(bias),
    .feature_out(feature_out)
);

Conv_gmem_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 32 ),
    .USER_AW( 32 ),
    .USER_MAXREQS( 5 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
Conv_gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(1'd0),
    .I_ARLEN(32'd1),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_addr_1_reg_1524),
    .I_AWID(1'd0),
    .I_AWLEN(32'd1),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(sum_4_reg_1636),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(4'd15),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

Conv_fadd_32ns_32bkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Conv_fadd_32ns_32bkb_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_473_p0),
    .din1(grp_fu_473_p1),
    .ce(1'b1),
    .dout(grp_fu_473_p2)
);

Conv_fmul_32ns_32cud #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Conv_fmul_32ns_32cud_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(gmem_addr_2_read_reg_1604),
    .din1(gmem_addr_3_read_reg_1609),
    .ce(1'b1),
    .dout(grp_fu_479_p2)
);

Conv_fcmp_32ns_32dEe #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
Conv_fcmp_32ns_32dEe_U3(
    .din0(sum_3_reg_1629),
    .din1(32'd0),
    .opcode(5'd4),
    .dout(tmp_28_fu_483_p2)
);

Conv_sdiv_19s_9nseOg #(
    .ID( 1 ),
    .NUM_STAGE( 23 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
Conv_sdiv_19s_9nseOg_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_700_ap_start),
    .done(grp_fu_700_ap_done),
    .din0(grp_fu_700_p0),
    .din1(grp_fu_700_p1),
    .ce(1'b1),
    .dout(grp_fu_700_p2)
);

Conv_sdiv_19s_9nseOg #(
    .ID( 1 ),
    .NUM_STAGE( 23 ),
    .din0_WIDTH( 19 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 16 ))
Conv_sdiv_19s_9nseOg_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .start(grp_fu_746_ap_start),
    .done(grp_fu_746_ap_done),
    .din0(grp_fu_746_p0),
    .din1(grp_fu_746_p1),
    .ce(1'b1),
    .dout(grp_fu_746_p2)
);

Conv_mul_mul_16nsfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Conv_mul_mul_16nsfYi_U6(
    .din0(ret_V_fu_1198_p0),
    .din1(ret_V_fu_1198_p1),
    .dout(ret_V_fu_1198_p2)
);

Conv_mul_mul_16s_g8j #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Conv_mul_mul_16s_g8j_U7(
    .din0(h_V_fu_931_p2),
    .din1(ret_V_9_fu_1203_p1),
    .dout(ret_V_9_fu_1203_p2)
);

Conv_mul_mul_16nsfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
Conv_mul_mul_16nsfYi_U8(
    .din0(ret_V_10_fu_1208_p0),
    .din1(ret_V_10_fu_1208_p1),
    .dout(ret_V_10_fu_1208_p2)
);

Conv_mac_muladd_1hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 48 ),
    .dout_WIDTH( 48 ))
Conv_mac_muladd_1hbi_U9(
    .din0(w_V_fu_1019_p2),
    .din1(grp_fu_1213_p1),
    .din2(ret_V_14_reg_1530),
    .dout(grp_fu_1213_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_ARREADY <= 1'b0;
    end else begin
        if ((((ap_sig_ioackin_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state35)) | ((ap_sig_ioackin_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state34)) | ((1'b0 == ap_block_state29_io) & (1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd1)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b0;
        end else if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state35)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state34)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd1)))) begin
            ap_reg_ioackin_gmem_ARREADY <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_AWREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state62)) begin
            if ((ap_sig_ioackin_gmem_AWREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b0;
            end else if ((gmem_AWREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_AWREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_ioackin_gmem_WREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state63)) begin
            if ((ap_sig_ioackin_gmem_WREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b0;
            end else if ((gmem_WREADY == 1'b1)) begin
                ap_reg_ioackin_gmem_WREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & (exitcond_fu_895_p2 == 1'd1))) begin
        i_op_assign_1_reg_299 <= i_reg_1453;
    end else if (((exitcond5_fu_818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        i_op_assign_1_reg_299 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        i_op_assign_2_reg_321 <= 16'd0;
    end else if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state68))) begin
        i_op_assign_2_reg_321 <= j_reg_1486;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (exitcond3_fu_1004_p2 == 1'd1))) begin
        i_op_assign_3_reg_367 <= ii_reg_1504;
    end else if (((exitcond_fu_895_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        i_op_assign_3_reg_367 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        i_op_assign_4_reg_402 <= jj_reg_1553;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        i_op_assign_4_reg_402 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        i_op_assign_reg_435 <= 16'd0;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        i_op_assign_reg_435 <= cin_reg_1582;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state26) & (exitcond1_fu_861_p2 == 1'd1))) begin
        i_op_assign_s_reg_288 <= cout_reg_1428;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        i_op_assign_s_reg_288 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state28) & (exitcond_fu_895_p2 == 1'd1))) begin
        phi_mul1_reg_310 <= next_mul1_reg_1445;
    end else if (((exitcond5_fu_818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        phi_mul1_reg_310 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        phi_mul3_reg_344 <= 16'd0;
    end else if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state68))) begin
        phi_mul3_reg_344 <= next_mul2_reg_1473;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (exitcond3_fu_1004_p2 == 1'd1))) begin
        ret_V_16_reg_378 <= next_mul4_reg_1496;
    end else if (((exitcond_fu_895_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        ret_V_16_reg_378 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        ret_V_17_reg_413 <= next_mul5_reg_1545;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        ret_V_17_reg_413 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        ret_V_18_reg_446 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        ret_V_18_reg_446 <= next_mul_reg_1593;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        ret_V_5_reg_332 <= 32'd0;
    end else if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state68))) begin
        ret_V_5_reg_332 <= next_mul3_reg_1478;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state33) & (exitcond2_fu_1072_p2 == 1'd1))) begin
        sum_1_be_reg_457 <= sum_2_reg_424;
    end else if ((((exitcond3_fu_1004_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state31) & (brmerge_fu_1037_p2 == 1'd1)) | ((tmp_33_fu_1050_p2 == 1'd0) & (brmerge_fu_1037_p2 == 1'd0) & (exitcond3_fu_1004_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state31)))) begin
        sum_1_be_reg_457 <= sum_1_reg_390;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state50)) begin
        sum_1_reg_390 <= sum_1_be_reg_457;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        sum_1_reg_390 <= sum_reg_355;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        sum_2_reg_424 <= sum_1_reg_390;
    end else if ((1'b1 == ap_CS_fsm_state49)) begin
        sum_2_reg_424 <= grp_fu_473_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & (exitcond3_fu_1004_p2 == 1'd1))) begin
        sum_reg_355 <= sum_1_reg_390;
    end else if (((exitcond_fu_895_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        sum_reg_355 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        CHin_V_read_reg_1267 <= CHin_V;
        CHout_V_read_reg_1249 <= CHout_V;
        Hin_V_read_reg_1262 <= Hin_V;
        Kx_V_read_reg_1242 <= Kx_V;
        Ky_V_read_reg_1236 <= Ky_V;
        Sx_V_read_reg_1230 <= Sx_V;
        Sy_V_read_reg_1224 <= Sy_V;
        Win_V_read_reg_1256 <= Win_V;
        p_1_reg_1300 <= p_1_fu_652_p3;
        p_s_reg_1294 <= p_s_fu_644_p3;
        relu_en_V_read_reg_1219 <= relu_en_V;
        tmp_1_reg_1274 <= {{feature_out[31:2]}};
        tmp_2_reg_1279 <= {{bias[31:2]}};
        tmp_4_reg_1284 <= {{W[31:2]}};
        tmp_5_reg_1289 <= {{feature_in[31:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        Wout_V_reg_1356 <= Wout_V_fu_768_p2;
        rhs_V_12_cast1_reg_1408[15 : 0] <= rhs_V_12_cast1_fu_809_p1[15 : 0];
        rhs_V_13_cast_reg_1414[15 : 0] <= rhs_V_13_cast_fu_812_p1[15 : 0];
        rhs_V_14_cast_reg_1419[15 : 0] <= rhs_V_14_cast_fu_815_p1[15 : 0];
        rhs_V_15_cast_reg_1403[7 : 0] <= rhs_V_15_cast_fu_806_p1[7 : 0];
        rhs_V_1_cast_reg_1376[15 : 0] <= rhs_V_1_cast_fu_790_p1[15 : 0];
        rhs_V_1_reg_1398[15 : 0] <= rhs_V_1_fu_803_p1[15 : 0];
        rhs_V_reg_1381[15 : 0] <= rhs_V_fu_794_p1[15 : 0];
        tmp_12_cast_reg_1346[29 : 0] <= tmp_12_cast_fu_758_p1[29 : 0];
        tmp_15_cast_reg_1351[29 : 0] <= tmp_15_cast_fu_761_p1[29 : 0];
        tmp_21_reg_1388[7 : 0] <= tmp_21_fu_797_p1[7 : 0];
        tmp_22_reg_1393[7 : 0] <= tmp_22_fu_800_p1[7 : 0];
        tmp_2_cast1_reg_1336[29 : 0] <= tmp_2_cast1_fu_752_p1[29 : 0];
        tmp_7_reg_1361 <= tmp_7_fu_778_p2;
        tmp_8_cast_reg_1341[29 : 0] <= tmp_8_cast_fu_755_p1[29 : 0];
        tmp_9_reg_1366[7 : 0] <= tmp_9_fu_784_p1[7 : 0];
        tmp_s_reg_1371[7 : 0] <= tmp_s_fu_787_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        cin_reg_1582 <= cin_fu_1077_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        cout_reg_1428 <= cout_fu_823_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state29_io) & (1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd1))) begin
        gmem_addr_1_reg_1524 <= feature_out8_sum_cas_fu_972_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state41))) begin
        gmem_addr_2_read_reg_1604 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_1072_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state33))) begin
        gmem_addr_2_reg_1587 <= feature_in2_sum9_cas_fu_1097_p1;
        gmem_addr_3_reg_1598 <= W4_sum_cast_fu_1135_p1;
        next_mul_reg_1593 <= next_mul_fu_1107_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state42))) begin
        gmem_addr_3_read_reg_1609 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
        gmem_addr_read_reg_1624 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5_fu_818_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        gmem_addr_reg_1439[30 : 0] <= bias6_sum_cast_fu_842_p1[30 : 0];
        tmp_10_cast_reg_1433[15 : 0] <= tmp_10_cast_fu_833_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state29_io) & (1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd0))) begin
        h_V_reg_1509 <= h_V_fu_931_p2;
        ret_V_9_reg_1514 <= ret_V_9_fu_1203_p2;
        slt_reg_1519 <= slt_fu_944_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state26)) begin
        i_reg_1453 <= i_fu_866_p2;
        next_mul1_reg_1445 <= next_mul1_fu_852_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state29_io) & (1'b1 == ap_CS_fsm_state29))) begin
        ii_reg_1504 <= ii_fu_921_p2;
        next_mul4_reg_1496 <= next_mul4_fu_911_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        j_reg_1486 <= j_fu_900_p2;
        next_mul2_reg_1473 <= next_mul2_fu_885_p2;
        next_mul3_reg_1478 <= next_mul3_fu_890_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        jj_reg_1553 <= jj_fu_1009_p2;
        next_mul5_reg_1545 <= next_mul5_fu_999_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        lhs_V_2_cast_reg_1306[15 : 0] <= lhs_V_2_cast_fu_671_p1[15 : 0];
        lhs_V_4_cast_reg_1321[15 : 0] <= lhs_V_4_cast_fu_717_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        ret_V_10_reg_1535 <= ret_V_10_fu_1208_p2;
        ret_V_14_reg_1530 <= ret_V_14_fu_985_p2;
        rev_reg_1540 <= rev_fu_994_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((brmerge_fu_1037_p2 == 1'd0) & (exitcond3_fu_1004_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state31) & (tmp_33_fu_1050_p2 == 1'd1))) begin
        ret_V_12_reg_1564 <= grp_fu_1213_p3;
        tmp_reg_1569 <= tmp_fu_1059_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state27)) begin
        ret_V_1_reg_1468 <= ret_V_1_fu_880_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_861_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state26))) begin
        ret_V_reg_1458 <= ret_V_fu_1198_p2;
        tmp_23_reg_1463 <= tmp_23_fu_872_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        sum_3_reg_1629 <= grp_fu_473_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state62))) begin
        sum_4_reg_1636 <= sum_4_fu_1191_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        tmp1_reg_1574 <= tmp1_fu_1067_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_895_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state28))) begin
        tmp_24_reg_1491 <= tmp_24_fu_906_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        tp_reg_1614 <= grp_fu_479_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (exitcond5_fu_818_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) & (exitcond5_fu_818_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_ARREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_ARREADY = gmem_ARREADY;
    end else begin
        ap_sig_ioackin_gmem_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_AWREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_AWREADY = gmem_AWREADY;
    end else begin
        ap_sig_ioackin_gmem_AWREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_WREADY == 1'b0)) begin
        ap_sig_ioackin_gmem_WREADY = gmem_WREADY;
    end else begin
        ap_sig_ioackin_gmem_WREADY = 1'b1;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_gmem_ARREADY == 1'b0)) begin
        if ((1'b1 == ap_CS_fsm_state35)) begin
            gmem_ARADDR = gmem_addr_3_reg_1598;
        end else if ((1'b1 == ap_CS_fsm_state34)) begin
            gmem_ARADDR = gmem_addr_2_reg_1587;
        end else if (((1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd1))) begin
            gmem_ARADDR = gmem_addr_reg_1439;
        end else begin
            gmem_ARADDR = 'bx;
        end
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_reg_ioackin_gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state35)) | ((ap_reg_ioackin_gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state34)) | ((ap_reg_ioackin_gmem_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd1)))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_gmem_AWREADY == 1'b0) & (1'b1 == ap_CS_fsm_state62))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state68))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state42)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state41)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state57)))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_ioackin_gmem_WREADY == 1'b0) & (1'b1 == ap_CS_fsm_state63))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state34) | ((1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd1)))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state62)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state57))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state63)) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        grp_fu_473_p0 = sum_reg_355;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_473_p0 = sum_2_reg_424;
    end else begin
        grp_fu_473_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        grp_fu_473_p1 = gmem_addr_read_reg_1624;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        grp_fu_473_p1 = tp_reg_1614;
    end else begin
        grp_fu_473_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_700_ap_start = 1'b1;
    end else begin
        grp_fu_700_ap_start = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_746_ap_start = 1'b1;
    end else begin
        grp_fu_746_ap_start = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((1'b1 == ap_CS_fsm_state25) & (exitcond5_fu_818_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            if (((1'b1 == ap_CS_fsm_state26) & (exitcond1_fu_861_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            if (((1'b1 == ap_CS_fsm_state28) & (exitcond_fu_895_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state29 : begin
            if (((1'b0 == ap_block_state29_io) & (1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state51;
            end else if (((1'b0 == ap_block_state29_io) & (1'b1 == ap_CS_fsm_state29) & (exitcond4_fu_916_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((1'b1 == ap_CS_fsm_state31) & (exitcond3_fu_1004_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end else if (((brmerge_fu_1037_p2 == 1'd0) & (exitcond3_fu_1004_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state31) & (tmp_33_fu_1050_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            if (((1'b1 == ap_CS_fsm_state33) & (exitcond2_fu_1072_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state34 : begin
            if (((ap_sig_ioackin_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            if (((ap_sig_ioackin_gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state35))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state41))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end
        end
        ap_ST_fsm_state42 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state42))) begin
                ap_NS_fsm = ap_ST_fsm_state43;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            if (((ap_sig_ioackin_gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state62))) begin
                ap_NS_fsm = ap_ST_fsm_state63;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state62;
            end
        end
        ap_ST_fsm_state63 : begin
            if (((ap_sig_ioackin_gmem_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state63))) begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state63;
            end
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            if (((gmem_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state68))) begin
                ap_NS_fsm = ap_ST_fsm_state28;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state68;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W4_sum_cast_fu_1135_p1 = W4_sum_fu_1130_p2;

assign W4_sum_fu_1130_p2 = (tmp_40_cast_cast_fu_1126_p1 + tmp_12_cast_reg_1346);

assign Wout_V_fu_768_p2 = (16'd1 + tmp_16_fu_764_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

always @ (*) begin
    ap_block_state29_io = ((ap_sig_ioackin_gmem_ARREADY == 1'b0) & (exitcond4_fu_916_p2 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bias6_sum_cast_fu_842_p1 = bias6_sum_fu_837_p2;

assign bias6_sum_fu_837_p2 = (tmp_10_cast1_fu_829_p1 + tmp_8_cast_reg_1341);

assign brmerge_fu_1037_p2 = (tmp_32_fu_1029_p3 | rev_reg_1540);

assign cin_fu_1077_p2 = (i_op_assign_reg_435 + 16'd1);

assign cout_fu_823_p2 = (i_op_assign_s_reg_288 + 16'd1);

assign exitcond1_fu_861_p2 = ((i_op_assign_1_reg_299 == tmp_7_reg_1361) ? 1'b1 : 1'b0);

assign exitcond2_fu_1072_p2 = ((i_op_assign_reg_435 == CHin_V_read_reg_1267) ? 1'b1 : 1'b0);

assign exitcond3_fu_1004_p2 = ((i_op_assign_4_reg_402 == Kx_V_read_reg_1242) ? 1'b1 : 1'b0);

assign exitcond4_fu_916_p2 = ((i_op_assign_3_reg_367 == Ky_V_read_reg_1236) ? 1'b1 : 1'b0);

assign exitcond5_fu_818_p2 = ((i_op_assign_s_reg_288 == CHout_V_read_reg_1249) ? 1'b1 : 1'b0);

assign exitcond_fu_895_p2 = ((i_op_assign_2_reg_321 == Wout_V_reg_1356) ? 1'b1 : 1'b0);

assign feature_in2_sum9_cas_fu_1097_p1 = $signed(feature_in2_sum9_fu_1092_p2);

assign feature_in2_sum9_fu_1092_p2 = (ret_V_15_fu_1087_p2 + tmp_15_cast_reg_1351);

assign feature_out8_sum_cas_fu_972_p1 = feature_out8_sum_fu_967_p2;

assign feature_out8_sum_fu_967_p2 = (tmp_2_cast1_reg_1336 + tmp_20_cast_cast_fu_963_p1);

assign grp_fu_1213_p1 = rhs_V_reg_1381;

assign grp_fu_700_p0 = $signed(ret_V_4_fu_687_p2);

assign grp_fu_700_p1 = grp_fu_700_p10;

assign grp_fu_700_p10 = Sx_V_read_reg_1230;

assign grp_fu_746_p0 = $signed(ret_V_8_fu_733_p2);

assign grp_fu_746_p1 = grp_fu_746_p10;

assign grp_fu_746_p10 = Sy_V_read_reg_1224;

assign h_V_fu_931_p2 = (tmp_23_reg_1463 + tmp_18_fu_927_p1);

assign i_fu_866_p2 = (i_op_assign_1_reg_299 + 16'd1);

assign ii_fu_921_p2 = (i_op_assign_3_reg_367 + 8'd1);

assign j_fu_900_p2 = (i_op_assign_2_reg_321 + 16'd1);

assign jj_fu_1009_p2 = (i_op_assign_4_reg_402 + 8'd1);

assign lhs_V_12_cast_fu_1055_p1 = ret_V_17_reg_413;

assign lhs_V_2_cast_fu_671_p1 = Win_V_read_reg_1256;

assign lhs_V_4_cast_fu_717_p1 = Hin_V_read_reg_1262;

assign lhs_V_5_cast_fu_1046_p1 = w_V_fu_1019_p2;

assign lhs_V_7_cast_fu_940_p1 = h_V_fu_931_p2;

assign next_mul1_fu_852_p2 = (phi_mul1_reg_310 + tmp_21_reg_1388);

assign next_mul2_fu_885_p2 = (phi_mul3_reg_344 + tmp_22_reg_1393);

assign next_mul3_fu_890_p2 = (ret_V_5_reg_332 + rhs_V_14_cast_reg_1419);

assign next_mul4_fu_911_p2 = (ret_V_16_reg_378 + rhs_V_15_cast_reg_1403);

assign next_mul5_fu_999_p2 = (ret_V_17_reg_413 + rhs_V_13_cast_reg_1414);

assign next_mul_fu_1107_p2 = (rhs_V_14_cast_reg_1419 + ret_V_18_reg_446);

assign notlhs_fu_1162_p2 = ((tmp_25_fu_1148_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_1168_p2 = ((tmp_26_fu_1158_p1 == 23'd0) ? 1'b1 : 1'b0);

assign or_cond_fu_1186_p2 = (tmp_31_fu_1180_p2 & relu_en_V_read_reg_1219);

assign p_1_fu_652_p3 = ((mode_V[0:0] === 1'b1) ? pad_y_V_fu_636_p3 : 8'd0);

assign p_neg9_fu_546_p2 = (9'd1 - tmp_2_cast_fu_528_p1);

assign p_neg_fu_604_p2 = (9'd1 - tmp_16_cast_fu_586_p1);

assign p_s_fu_644_p3 = ((mode_V[0:0] === 1'b1) ? pad_x_V_fu_578_p3 : 8'd0);

assign pad_x_V_fu_578_p3 = ((tmp_8_fu_538_p3[0:0] === 1'b1) ? tmp_6_fu_572_p2 : tmp_10_fu_562_p4);

assign pad_y_V_fu_636_p3 = ((tmp_11_fu_596_p3[0:0] === 1'b1) ? tmp_14_fu_630_p2 : tmp_13_fu_620_p4);

assign ret_V_10_fu_1208_p0 = ret_V_10_fu_1208_p00;

assign ret_V_10_fu_1208_p00 = ret_V_16_reg_378;

assign ret_V_10_fu_1208_p1 = rhs_V_reg_1381;

assign ret_V_14_fu_985_p0 = ret_V_9_reg_1514;

assign ret_V_14_fu_985_p1 = rhs_V_1_reg_1398;

assign ret_V_14_fu_985_p2 = ($signed(ret_V_14_fu_985_p0) * $signed({{1'b0}, {ret_V_14_fu_985_p1}}));

assign ret_V_15_fu_1087_p2 = ($signed(rhs_V_10_cast_fu_1083_p1) + $signed(ret_V_12_reg_1564));

assign ret_V_1_fu_880_p0 = ret_V_1_fu_880_p00;

assign ret_V_1_fu_880_p00 = ret_V_reg_1458;

assign ret_V_1_fu_880_p1 = rhs_V_12_cast1_reg_1408;

assign ret_V_1_fu_880_p2 = (ret_V_1_fu_880_p0 * ret_V_1_fu_880_p1);

assign ret_V_1_tr_fu_590_p2 = ($signed(9'd511) + $signed(tmp_16_cast_fu_586_p1));

assign ret_V_2_cast_fu_667_p1 = ret_V_2_fu_660_p3;

assign ret_V_2_fu_660_p3 = {{p_s_reg_1294}, {1'd0}};

assign ret_V_3_cast_fu_680_p1 = ret_V_3_fu_674_p2;

assign ret_V_3_fu_674_p2 = (lhs_V_2_cast_fu_671_p1 + ret_V_2_cast_fu_667_p1);

assign ret_V_4_fu_687_p2 = (ret_V_3_cast_fu_680_p1 - rhs_V_2_cast_fu_684_p1);

assign ret_V_6_cast_fu_713_p1 = ret_V_6_fu_706_p3;

assign ret_V_6_fu_706_p3 = {{p_1_reg_1300}, {1'd0}};

assign ret_V_7_cast_fu_726_p1 = ret_V_7_fu_720_p2;

assign ret_V_7_fu_720_p2 = (lhs_V_4_cast_fu_717_p1 + ret_V_6_cast_fu_713_p1);

assign ret_V_8_fu_733_p2 = (ret_V_7_cast_fu_726_p1 - rhs_V_5_cast_fu_730_p1);

assign ret_V_9_fu_1203_p1 = rhs_V_reg_1381;

assign ret_V_fu_1198_p0 = ret_V_fu_1198_p00;

assign ret_V_fu_1198_p00 = i_op_assign_1_reg_299;

assign ret_V_fu_1198_p1 = rhs_V_1_cast_reg_1376;

assign ret_V_tr_fu_532_p2 = ($signed(9'd511) + $signed(tmp_2_cast_fu_528_p1));

assign rev_fu_994_p2 = (slt_reg_1519 ^ 1'd1);

assign rhs_V_10_cast_fu_1083_p1 = i_op_assign_reg_435;

assign rhs_V_12_cast1_fu_809_p1 = CHout_V_read_reg_1249;

assign rhs_V_13_cast_fu_812_p1 = CHin_V_read_reg_1267;

assign rhs_V_14_cast_fu_815_p1 = CHout_V_read_reg_1249;

assign rhs_V_15_cast_fu_806_p1 = Kx_V_read_reg_1242;

assign rhs_V_1_cast_fu_790_p1 = Wout_V_fu_768_p2;

assign rhs_V_1_fu_803_p1 = Win_V_read_reg_1256;

assign rhs_V_2_cast_fu_684_p1 = Kx_V_read_reg_1242;

assign rhs_V_5_cast_fu_730_p1 = Ky_V_read_reg_1236;

assign rhs_V_fu_794_p1 = CHin_V_read_reg_1267;

assign slt_fu_944_p2 = (($signed(lhs_V_7_cast_fu_940_p1) < $signed(lhs_V_4_cast_reg_1321)) ? 1'b1 : 1'b0);

assign sum_4_fu_1191_p3 = ((or_cond_fu_1186_p2[0:0] === 1'b1) ? 32'd0 : sum_3_reg_1629);

assign sum_5_to_int_fu_1145_p1 = sum_3_reg_1629;

assign tmp1_fu_1067_p0 = tmp1_fu_1067_p00;

assign tmp1_fu_1067_p00 = tmp_reg_1569;

assign tmp1_fu_1067_p1 = rhs_V_12_cast1_reg_1408;

assign tmp1_fu_1067_p2 = (tmp1_fu_1067_p0 * tmp1_fu_1067_p1);

assign tmp2_cast_fu_1117_p1 = tmp2_fu_1112_p2;

assign tmp2_fu_1112_p2 = (tmp_10_cast_reg_1433 + ret_V_18_reg_446);

assign tmp3_cast_fu_954_p1 = tmp3_fu_949_p2;

assign tmp3_fu_949_p2 = (tmp_10_cast_reg_1433 + ret_V_5_reg_332);

assign tmp_10_cast1_fu_829_p1 = i_op_assign_s_reg_288;

assign tmp_10_cast_fu_833_p1 = i_op_assign_s_reg_288;

assign tmp_10_fu_562_p4 = {{ret_V_tr_fu_532_p2[8:1]}};

assign tmp_11_fu_596_p3 = ret_V_1_tr_fu_590_p2[32'd8];

assign tmp_12_cast_fu_758_p1 = tmp_4_reg_1284;

assign tmp_12_fu_610_p4 = {{p_neg_fu_604_p2[8:1]}};

assign tmp_13_fu_620_p4 = {{ret_V_1_tr_fu_590_p2[8:1]}};

assign tmp_14_fu_630_p2 = (8'd0 - tmp_12_fu_610_p4);

assign tmp_15_cast_fu_761_p1 = tmp_5_reg_1289;

assign tmp_16_cast_fu_586_p1 = Ky_V;

assign tmp_16_fu_764_p1 = grp_fu_700_p2[15:0];

assign tmp_18_fu_927_p1 = i_op_assign_3_reg_367;

assign tmp_19_fu_774_p1 = grp_fu_746_p2[15:0];

assign tmp_20_cast_cast_fu_963_p1 = tmp_20_fu_958_p2;

assign tmp_20_fu_958_p2 = (ret_V_1_reg_1468 + tmp3_cast_fu_954_p1);

assign tmp_21_fu_797_p1 = Sy_V_read_reg_1224;

assign tmp_22_fu_800_p1 = Sx_V_read_reg_1230;

assign tmp_23_fu_872_p2 = (phi_mul1_reg_310 - tmp_9_reg_1366);

assign tmp_24_fu_906_p2 = (phi_mul3_reg_344 - tmp_s_reg_1371);

assign tmp_25_fu_1148_p4 = {{sum_5_to_int_fu_1145_p1[30:23]}};

assign tmp_26_fu_1158_p1 = sum_5_to_int_fu_1145_p1[22:0];

assign tmp_27_fu_1174_p2 = (notrhs_fu_1168_p2 | notlhs_fu_1162_p2);

assign tmp_29_fu_1015_p1 = i_op_assign_4_reg_402;

assign tmp_2_cast1_fu_752_p1 = tmp_1_reg_1274;

assign tmp_2_cast_fu_528_p1 = Kx_V;

assign tmp_30_fu_1024_p2 = (w_V_fu_1019_p2 | h_V_reg_1509);

assign tmp_31_fu_1180_p2 = (tmp_28_fu_483_p2 & tmp_27_fu_1174_p2);

assign tmp_32_fu_1029_p3 = tmp_30_fu_1024_p2[32'd15];

assign tmp_33_fu_1050_p2 = (($signed(lhs_V_5_cast_fu_1046_p1) < $signed(lhs_V_2_cast_reg_1306)) ? 1'b1 : 1'b0);

assign tmp_34_fu_1121_p2 = (tmp1_reg_1574 + tmp2_cast_fu_1117_p1);

assign tmp_3_fu_552_p4 = {{p_neg9_fu_546_p2[8:1]}};

assign tmp_40_cast_cast_fu_1126_p1 = tmp_34_fu_1121_p2;

assign tmp_6_fu_572_p2 = (8'd0 - tmp_3_fu_552_p4);

assign tmp_7_fu_778_p2 = (16'd1 + tmp_19_fu_774_p1);

assign tmp_8_cast_fu_755_p1 = tmp_2_reg_1279;

assign tmp_8_fu_538_p3 = ret_V_tr_fu_532_p2[32'd8];

assign tmp_9_fu_784_p1 = p_1_reg_1300;

assign tmp_fu_1059_p2 = (ret_V_10_reg_1535 + lhs_V_12_cast_fu_1055_p1);

assign tmp_s_fu_787_p1 = p_s_reg_1294;

assign w_V_fu_1019_p2 = (tmp_24_reg_1491 + tmp_29_fu_1015_p1);

always @ (posedge ap_clk) begin
    lhs_V_2_cast_reg_1306[16] <= 1'b0;
    lhs_V_4_cast_reg_1321[16] <= 1'b0;
    tmp_2_cast1_reg_1336[48:30] <= 19'b0000000000000000000;
    tmp_8_cast_reg_1341[30] <= 1'b0;
    tmp_12_cast_reg_1346[48:30] <= 19'b0000000000000000000;
    tmp_15_cast_reg_1351[47:30] <= 18'b000000000000000000;
    tmp_9_reg_1366[15:8] <= 8'b00000000;
    tmp_s_reg_1371[15:8] <= 8'b00000000;
    rhs_V_1_cast_reg_1376[31:16] <= 16'b0000000000000000;
    rhs_V_reg_1381[31:16] <= 16'b0000000000000000;
    tmp_21_reg_1388[15:8] <= 8'b00000000;
    tmp_22_reg_1393[15:8] <= 8'b00000000;
    rhs_V_1_reg_1398[47:16] <= 32'b00000000000000000000000000000000;
    rhs_V_15_cast_reg_1403[15:8] <= 8'b00000000;
    rhs_V_12_cast1_reg_1408[47:16] <= 32'b00000000000000000000000000000000;
    rhs_V_13_cast_reg_1414[23:16] <= 8'b00000000;
    rhs_V_14_cast_reg_1419[31:16] <= 16'b0000000000000000;
    tmp_10_cast_reg_1433[31:16] <= 16'b0000000000000000;
    gmem_addr_reg_1439[31] <= 1'b0;
end

endmodule //Conv
